quarkus.rest-client.situacao-cadastral-api.uri = http://localhost:8181
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=estudo_quarkus
quarkus.datasource.password=estudo_quarkus_1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/agencia
quarkus.hibernate-orm.database.generation=update